#!/usr/bin/env bash
#
# 75-install-boot.sh — make the stack survive a reboot, and self-heal.
#
# Installs two pieces, both Termux-native and both fail-soft (a missing addon is
# a warning, never a hard error):
#
#   1. A Termux:Boot launcher (~/.termux/boot/00-pocket-homeserver.sh) that, on
#      phone boot, acquires a wake-lock, clears stale pidfiles, and runs the
#      idempotent full-stack bring-up (start-stack.sh) — so the whole stack comes
#      back automatically after a reboot. Requires the **Termux:Boot** addon app
#      (install it from F-Droid and open it once; this step just writes the file).
#
#   2. A JobScheduler **watchdog** (scripts/watchdog.sh, ~15 min, persisted) that
#      re-runs the same idempotent bring-up, so a supervisor reaped by Android's
#      low-memory killer is respawned without waiting for a reboot. Requires the
#      **Termux:API** addon app + `pkg install termux-api` (provides
#      termux-job-scheduler). If absent, reboot survival still works; only the
#      watchdog is skipped.
#
# Self-gates on ENABLE_BOOT (default true). Idempotent — safe to re-run.
#
# Generalized from a working deployment; review before running on a fresh phone.

set -euo pipefail
. "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/lib/common.sh"

load_env

if [ "${ENABLE_BOOT:-true}" != "true" ]; then
  ok "ENABLE_BOOT is not true — skipping reboot-survival + watchdog setup"
  exit 0
fi

require_var DATA_DIR "folder on your large volume / SD card"

# This step is Termux-native (it writes ~/.termux/boot and talks to JobScheduler,
# neither of which exists inside the proot userland). If we're not on Termux,
# there's nothing to install — warn and succeed (e.g. a laptop dry-run).
if ! command -v pkg >/dev/null 2>&1; then
  warn "not running on Termux (no 'pkg') — skipping boot/watchdog setup (run it on the phone)"
  exit 0
fi

PREFIX_DIR="${PREFIX:-/data/data/com.termux/files/usr}"
BOOT_DIR="$HOME/.termux/boot"
BOOT_SCRIPT="$BOOT_DIR/00-pocket-homeserver.sh"

# ── 1. Termux:Boot launcher ───────────────────────────────────────────────────
# We write ONLY our own launcher (never wipe the dir — the user may have other
# Termux:Boot scripts). Paths are baked in expanded so the launcher needs no
# environment; start-stack.sh re-derives everything from .env itself.
mkdir -p "$BOOT_DIR"
umask 077
cat > "$BOOT_SCRIPT" <<EOF
#!${PREFIX_DIR}/bin/bash
# Auto-generated by pocket-homeserver scripts/steps/75-install-boot.sh.
# Runs on phone boot via the Termux:Boot addon. Brings the whole stack back up.
termux-wake-lock 2>/dev/null || true
# Stale-pidfile wipe: after a reboot every state/*.pid still holds a PID from the
# previous boot. If Android reused that PID for another process, a liveness check
# could falsely report "already running" and skip the service. Nothing is running
# yet at boot, so wiping is always safe.
rm -f "${POCKET_STATE_DIR}"/*.pid 2>/dev/null || true
sleep 10   # let Android's network settle
exec bash "${POCKET_ROOT}/scripts/start-stack.sh" >> "${POCKET_LOG_DIR}/boot.log" 2>&1
EOF
chmod 700 "$BOOT_SCRIPT"
ok "wrote Termux:Boot launcher → $BOOT_SCRIPT"
if [ ! -d "$HOME/.termux/boot" ] || ! pkg list-installed 2>/dev/null | grep -qi termux-boot; then
  say "Reboot survival needs the Termux:Boot addon app (F-Droid). Install it and open"
  say "it once so Android lets it run at boot; the launcher above is already in place."
fi

# ── 2. JobScheduler watchdog (optional; needs Termux:API) ─────────────────────
WATCHDOG="${POCKET_ROOT}/scripts/watchdog.sh"
[ -f "$WATCHDOG" ] || die "missing $WATCHDOG (it ships with the repo) — cannot register the watchdog"

if ! command -v termux-job-scheduler >/dev/null 2>&1; then
  warn "termux-job-scheduler not found — skipping the self-heal watchdog."
  say  "To enable it: install the Termux:API addon app (F-Droid) + 'pkg install termux-api', then re-run."
  ok   "boot setup complete (reboot survival installed; watchdog deferred until Termux:API is present)"
  exit 0
fi

# termux-job-scheduler --script must point at an EXECUTABLE file. The SD card is
# often FAT/exFAT, which does NOT honor the exec bit, so a launcher there is
# refused ("Cannot execute file"). Write a tiny launcher on ext4 ($HOME, where
# the exec bit sticks) that runs the repo's watchdog via bash — so watchdog.sh
# stays the single source of truth wherever the repo lives.
LAUNCH_DIR="$HOME/.pocket"
LAUNCHER="$LAUNCH_DIR/watchdog-launcher.sh"
JOB_ID=4242            # fixed id => re-runs overwrite, never duplicate
PERIOD_MS=900000       # ~15 min (Android N+ enforced minimum)

mkdir -p "$LAUNCH_DIR"
cat > "$LAUNCHER" <<EOF
#!${PREFIX_DIR}/bin/bash
# Auto-generated by pocket-homeserver. Exec-bit-honored launcher (ext4) for the
# JobScheduler watchdog; the real logic is the repo copy below.
exec bash "$WATCHDOG"
EOF
chmod 700 "$LAUNCHER"

say "registering the watchdog with JobScheduler (job-id $JOB_ID, every ${PERIOD_MS}ms, persisted)"
# --battery-not-low false: heal even on low battery (the default true would
# suppress the watchdog exactly when a struggling phone most needs it).
termux-job-scheduler \
  --script "$LAUNCHER" \
  --job-id "$JOB_ID" \
  --period-ms "$PERIOD_MS" \
  --persisted true \
  --battery-not-low false \
  || warn "termux-job-scheduler registration call returned an error (verifying below)"

# termux-job-scheduler can exit 0 even when it didn't register, so do a REAL
# post-check: the job id must actually appear in --pending.
if termux-job-scheduler --pending 2>/dev/null | grep -q "$JOB_ID"; then
  ok "watchdog registered — Android re-runs start-stack every ~15 min (survives app-kill + reboot)"
  say "  verify any time:  termux-job-scheduler --pending   |   tail -f ${POCKET_LOG_DIR}/watchdog.log"
else
  warn "watchdog registration did NOT take (job-id $JOB_ID absent from --pending) — check that the"
  warn "Termux:API app is installed and $LAUNCHER is executable, then re-run this step."
fi

ok "boot setup complete (reboot survival + self-heal watchdog)"
